_core:
  default_config_hash: 0yJNd4uWv8TzhYEPQBDiApPL2e8ar88kBmQrzDjNCqc
nid_list: {  }
translation_sync: true
search: false
type: hidden
content_types:
  article: none
  page: all
content_type_modes:
  article: {  }
  page:
    - full
    - teaser
