_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 4e417a82-7ef5-4aeb-b3c6-a789bf8c3840
name: 'Orchard Test'
mail: carfelcoper@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/11
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
